dist: xenial
language: cpp
compiler:
  - g++-8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - cmake

before_install:
  - export CC=gcc-8
  - export CXX=g++-8
  - bash ./build_scripts/build_vcpkg.sh
  - export VCPKG_ROOT="$(pwd -P)/vcpkg"
  - export PATH="${PATH}:${VCPKG_ROOT}"

install:
  - vcpkg install catch2

script:
  -  mkdir build | echo exist
  - cd build
  - cmake -D CMAKE_BUILD_TYPE:STRING=Debug ..
  - cmake --build ./ -j 8
  - ctest -C Debug -V
  - cd ..

cache:
  directories:
  - vcpkg
  - build