#include "LeetCode.hpp"

/*
389. Find the Difference
Easy

Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.
Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

Tags: 
    1. Hash Table
    2. Bit Manipulation

Similar Questions:
    1. Single Number

*/

class Solution {
public:
    char findTheDifference(string s, string t) {
        
    }
};

TEST_CASE("find-the-difference", "[389][Easy][hash-table][bit-manipulation]") {
    //TODO
    CHECK(true);
}

